---
services:
  ########## Container Management  ##########
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.2
    container_name: homepage
    networks: [traefik_proxy, socket_proxy]
    restart: unless-stopped
    ports: [3020:3000]
    volumes:
      - $DOCKER_DIR/data/homepage:/app/config  # Make sure your local config directory exists
      # - /var/run/docker.sock:/var/run/docker.sock:ro  # (optional) For docker integrations
      - $MEDIA_DIR:/mnt/media:ro
    environment:
      - PUID
      - PGID
      - TZ
      - HOMEPAGE_ALLOWED_HOSTS=homepage.${DOMAIN_NAME}
    labels:
      - traefik.enable=true
      - homepage.group=Management
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.description=Dashboard and service overview
      - homepage.href=https://homepage.${DOMAIN_NAME}
      ## HTTP Routers
      - traefik.http.routers.homepage-rtr.entrypoints=https
      - traefik.http.routers.homepage-rtr.rule=Host(`homepage.${DOMAIN_NAME}`)
      - traefik.http.routers.homepage-rtr.tls=true
      ## Middlewares
      - traefik.http.routers.homepage-rtr.middlewares=chain-oauth@file
      ## HTTP Services
      - traefik.http.routers.homepage-rtr.service=homepage-svc
      - traefik.http.services.homepage-svc.loadbalancer.server.port=3000
networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true
