---
http:
  routers:
    hass-rtr:
      entryPoints: [https]
      rule: Host(`hass.{{ env "DOMAIN_NAME" }}`)
      service: hass-svc
      middlewares: [chain-noauth]
  services:
    hass-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://10.0.10.238:8123
