---
http:
  middlewares:
    chain-oauth:
      chain:
        middlewares:
          # Apply authentication first so auth handlers see the original request
          [crowdsec, oidc-auth]
    chain-noauth:
      chain:
        middlewares: [crowdsec]
