http:
  middlewares:
    chain-oauth:
      chain:
        middlewares:
          # Apply authentication first so auth handlers see the original request
          - oidc-auth          
          - crowdsec
    chain-noauth:
      chain:
        middlewares:
          - crowdsec
