---
all:
  children:
    proxmox:
      hosts:
        heimdall:
          ansible_host: 10.0.10.20
          ansible_user: root

    vms:
      hosts:
        ubuntu-server-primary:
          ansible_host: 10.0.10.30
          ansible_user: alex
        ubuntu-devops:
          ansible_host: 10.0.10.60
          ansible_user: alex
        home-assistant:
          ansible_host: 10.0.10.15
          ansible_user: ubuntu
        pterodactyl-wing:
          ansible_host: 10.0.10.17
          ansible_user: ubuntu
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: /root/.ssh/homelab-runner

    lxc_containers:
      hosts:
        tailscale:
          ansible_host: 10.0.10.10
        forgejo:
          ansible_host: 10.0.10.18
        beszel:
          ansible_host: 10.0.10.12
        plex:
          ansible_host: 10.0.10.13
          lxc_id: 113
          needs_gpu: true
        pterodactyl-panel:
          ansible_host: 10.0.10.16
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: ssh
        ansible_ssh_private_key_file: /root/.ssh/homelab-runner

    media_servers:
      hosts:
        plex:
  vars:
    truenas_nfs_server: 10.0.10.25
    truenas_media_share: /mnt/primary/media
    truenas_downloads_share: /mnt/primary/downloads
