---
services:
  # CrowdSec - Open-source & collaborative security IPS
  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.8
    container_name: crowdsec
    networks: [traefik_proxy, socket_proxy]
    expose:
      - 8080  # http api for bouncers
      - 6060  # metrics endpoint for prometheus
      - 7422  # appsec waf endpoint
      # - "$CROWDSEC_PROMETHEUS_EXPORT:6060" # For metrics export to Prometheus database.
      # - "$ZEROTIER_IP_WEBSERVER:$CROWDSEC_PROMETHEUS_EXPORT:6060" # If you don't use ZeroTier remove use just $CROWDSEC_PROMETHEUS_EXPORT:6060
    environment:
      - COLLECTIONS= crowdsecurity/traefik crowdsecurity/http-dos crowdsecurity/http-cve
         crowdsecurity/base-http-scenarios crowdsecurity/iptables crowdsecurity/whitelist-good-actors
         crowdsecurity/nginx crowdsecurity/linux crowdsecurity/appsec-generic-rules
         crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-crs
      - TZ
    volumes:
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      - $DOCKER_DIR/data/traefik/logs:/var/log/traefik:ro
      - $DOCKER_DIR/data/crowdsec:/var/lib/crowdsec/data
      - $DOCKER_DIR/data/crowdsec/config:/etc/crowdsec
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - ps -ef | grep -v grep | grep -q '[c]rowdsec' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.9.0
    container_name: pocket-id
    restart: unless-stopped
    networks: [traefik_proxy, socket_proxy]
    ports: [1411:1411]
    environment:
      # adjust these
      - APP_URL=https://auth.${DOMAIN_NAME}
      - TRUST_PROXY=true
      - COOKIE_DOMAIN=.${DOMAIN_NAME}
      - ENCRYPTION_KEY=${POCKETID_ENCRYPTION_KEY}
      - PUID
      - PGID
      # other env vars (DB, etc) as needed
    volumes: [$DOCKER_DIR/data/pocketid:/app/data]
    labels:
      # Traefik Labels
      - traefik.enable=true
      # HTTP Routers
      - traefik.http.routers.pocketid-rtr.entrypoints=https
      - traefik.http.routers.pocketid-rtr.rule=Host(`auth.${DOMAIN_NAME}`)
      # Middlewares
      # - "traefik.http.routers.pocketid-rtr.middlewares=chain-noauth@file"
      # HTTP Services
      - traefik.http.routers.pocketid-rtr.service=pocketid-svc
      - traefik.http.services.pocketid-svc.loadbalancer.server.port=1411
    healthcheck:
      test: [CMD-SHELL, curl -f http://127.0.0.1:1411/ || exit 1]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true
