---
services:
  docker-in-docker:
    image: docker:dind
    extra_hosts:
      - "registry.louhome.xyz:10.0.10.30"
    container_name: docker_dind
    privileged: true
    ports:
      - "2375:2375"
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    restart: unless-stopped

  runner:
    image: data.forgejo.org/forgejo/runner:12
    extra_hosts:
      - "registry.louhome.xyz:10.0.10.30"
    container_name: runner
    restart: unless-stopped
    user: "1001:1001"
    depends_on:
      docker-in-docker:
        condition: service_started
    volumes:
      - /opt/docker/runner/data:/data
    network_mode: "host"
    command: ["forgejo-runner", "-c", "/data/runner-config.yml", "daemon"]
